# syntax=docker/dockerfile:1.7

# --- deps ---------------------------------------------------------------
FROM node:20-bookworm-slim AS deps
WORKDIR /app
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable && apt-get update && apt-get install -y --no-install-recommends \
      python3 make g++ \
    && rm -rf /var/lib/apt/lists/*
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# --- build --------------------------------------------------------------
FROM node:20-bookworm-slim AS builder
WORKDIR /app
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
ENV NEXT_TELEMETRY_DISABLED=1
RUN corepack enable
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build
# `public/` is optional in this project; ensure it exists so the runtime
# COPY below always has a source and the build never breaks.
RUN mkdir -p public

# --- runtime ------------------------------------------------------------
FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0 \
    DATABASE_URL=/app/data/r2c.db \
    DATA_DIR=/app/data

# `gosu` lets the entrypoint drop from root to the host-provided PUID/PGID.
RUN apt-get update && apt-get install -y --no-install-recommends gosu \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs \
    && mkdir -p /app/data && chown -R nextjs:nodejs /app/data

# next.config.ts sets `output: "standalone"`. The build output bundles the
# minimum server + node_modules required at runtime.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/src/lib/db/migrations ./src/lib/db/migrations
COPY --from=builder --chown=nextjs:nodejs /app/mapping.config.json ./mapping.config.json
COPY --chmod=755 docker-entrypoint.sh /app/docker-entrypoint.sh

# NOTE: we intentionally do NOT set `USER nextjs` here. The container starts as
# root so docker-entrypoint.sh can align the runtime user with the host's
# PUID/PGID and chown the bind-mounted data dir, then drops privileges via gosu.
EXPOSE 3000
VOLUME ["/app/data"]

# server.js is generated by Next.js standalone output.
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["node", "server.js"]
